# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch # importing torch

# checking torch version
torch.__version__



'2.2.1+cu121'

In [ ]:
#creating random tensor with shape (7,7) & it'll look like a 7 x 7 matrix
Random_Matrix1 = torch.rand(size = (7,7))
Random_Matrix1

tensor([[0.5612, 0.6824, 0.5404, 0.7569, 0.1567, 0.4715, 0.3153],
        [0.8495, 0.9572, 0.4571, 0.9036, 0.5705, 0.0171, 0.3455],
        [0.9675, 0.4411, 0.7994, 0.8863, 0.3448, 0.9164, 0.6624],
        [0.1243, 0.8253, 0.0673, 0.2584, 0.7214, 0.6946, 0.0221],
        [0.8394, 0.2405, 0.4475, 0.8977, 0.7954, 0.8638, 0.3137],
        [0.4709, 0.7115, 0.8176, 0.2468, 0.8784, 0.1455, 0.8774],
        [0.8383, 0.7369, 0.2903, 0.8740, 0.5317, 0.4742, 0.7058]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
Random_Matrix2 = torch.rand(size = (1,7))
Random_Matrix2

tensor([[0.7506, 0.0740, 0.1655, 0.6314, 0.5308, 0.8223, 0.6607]])

In [ ]:
# Perform matrix multiplication
# now matrix 1's size = 7,7 matrix 2's is 1,7 , hence transposing 2, to get size 7,1:
# finally we get a 7,1 matrix
print(Random_Matrix1,"\n\n", Random_Matrix2.T)
print() # extra line space
# using @ (not recommended)
print("MATRIX MULTIPLICATION YIELDS:")
Random_Matrix1 @ Random_Matrix2.T

tensor([[0.5612, 0.6824, 0.5404, 0.7569, 0.1567, 0.4715, 0.3153],
        [0.8495, 0.9572, 0.4571, 0.9036, 0.5705, 0.0171, 0.3455],
        [0.9675, 0.4411, 0.7994, 0.8863, 0.3448, 0.9164, 0.6624],
        [0.1243, 0.8253, 0.0673, 0.2584, 0.7214, 0.6946, 0.0221],
        [0.8394, 0.2405, 0.4475, 0.8977, 0.7954, 0.8638, 0.3137],
        [0.4709, 0.7115, 0.8176, 0.2468, 0.8784, 0.1455, 0.8774],
        [0.8383, 0.7369, 0.2903, 0.8740, 0.5317, 0.4742, 0.7058]]) 

 tensor([[0.7506],
        [0.0740],
        [0.1655],
        [0.6314],
        [0.5308],
        [0.8223],
        [0.6607]])

MATRIX MULTIPLICATION YIELDS:


tensor([[1.7182],
        [1.8999],
        [2.8250],
        [1.2974],
        [2.6285],
        [1.8629],
        [2.4220]])

In [ ]:
#using matmul:
torch.matmul(Random_Matrix1,Random_Matrix2.T)

tensor([[1.7182],
        [1.8999],
        [2.8250],
        [1.2974],
        [2.6285],
        [1.8629],
        [2.4220]])

In [ ]:
#manually:
answer = torch.zeros(size=(7, 1))
ind = 0
for i in Random_Matrix1:
  for j in Random_Matrix2:
     M = i * j
     answer[ind] = M.sum()
     ind += 1
answer

tensor([[1.7182],
        [1.8999],
        [2.8250],
        [1.2974],
        [2.6285],
        [1.8629],
        [2.4220]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
random_seed = 0
torch.manual_seed(seed = random_seed)

# Create two random tensors
A  = torch.rand(size = (7,7))
B = torch.rand(size = (1,7))
print(A, "\n\n", B)
print()

# Matrix multiply tensors
C = torch.matmul(A,B.T)
print("MATRIX MULTIPLICATION RESULT:")
print(C,C.shape)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) 

 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

MATRIX MULTIPLICATION RESULT:
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(seed = 1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:",device)

# Create two random tensors on GPU
A  = torch.rand(size = (2,3))
B = torch.rand(size = (2,3))

A_gpu = A.to(device)
B_gpu = B.to(device)
print(A_gpu,'\n\n',B_gpu)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') 

 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(A_gpu, B_gpu.T)
print(output, output.shape)
output.device

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


device(type='cuda', index=0)

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print("max:",output.max())
# Find min
print("min:",output.min())

max: tensor(0.5617, device='cuda:0')
min: tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"max value occurs at index:{output.argmax()}")
# Find arg min
print(f"min value occurs at index: {output.argmin()}")

max value occurs at index:3
min value occurs at index: 0


In [ ]:
# Find arg max
print("max value occurs at index", output.argmax())
# Find arg min
print("min value occurs at index", output.argmin())

max value occurs at index tensor(3, device='cuda:0')
min value occurs at index tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor1 = torch.rand(size = (1,1,1,10))

# Remove single dimensions
# method 1:
tensor1_reshaped = tensor1.reshape(10)
# method 2:
tensor1_squeeze = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1, tensor1.shape)
print()
print(tensor1_reshaped, tensor1_reshaped.shape)
print()
print(tensor1_squeeze, tensor1_squeeze.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
